### ISSUE TITLE
File Not Found 'LLaVA-Plus/llava/serve/examples/tbs.webp'

### ISSUE THREAD

**Issue by tranvanhoa533** [LLaVA-VL/LLaVA-Plus-Codebase#5]
### Describe the issue

Issue:
 FileNotFoundError: [Errno 2] No such file or directory: 'LLaVA-Plus/llava/serve/examples/tbs.webp'
Command:
```
python -m llava.serve.gradio_web_server_llava_plus --controller http://localhost:6001 --model-list-mode reload
```

Log: 
```
[2023-11-14 09:12:49,262] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Using conversation: conv_vicuna_v1
2023-11-14 09:12:50 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:6001', concurrency_count=8, model_list_mode='reload', share=False, moderate=False, embed=False, debug=False, with_debug_parameter=False)
2023-11-14 09:12:50 | INFO | gradio_web_server | Models: ['llava_plus_v0_7b']
2023-11-14 09:12:50 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:6001', concurrency_count=8, model_list_mode='reload', share=False, moderate=False, embed=False, debug=False, with_debug_parameter=False)
2023-11-14 09:12:51 | ERROR | stderr | /data/miniconda3/envs/llava/lib/python3.10/site-packages/gradio/blocks.py:261: UserWarning: api_name load_example already exists, using load_example_1
2023-11-14 09:12:51 | ERROR | stderr |   warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
2023-11-14 09:12:51 | ERROR | stderr | Traceback (most recent call last):
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-11-14 09:12:51 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
2023-11-14 09:12:51 | ERROR | stderr |     exec(code, run_globals)
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/hoatv2/codes/LLaVA-Plus/llava/serve/gradio_web_server_llava_plus.py", line 953, in <module>
2023-11-14 09:12:51 | ERROR | stderr |     demo = build_demo(args.embed)
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/hoatv2/codes/LLaVA-Plus/llava/serve/gradio_web_server_llava_plus.py", line 844, in build_demo
2023-11-14 09:12:51 | ERROR | stderr |     gr.Examples(examples=[
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/site-packages/gradio/helpers.py", line 54, in create_examples
2023-11-14 09:12:51 | ERROR | stderr |     examples_obj = Examples(
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/site-packages/gradio/helpers.py", line 201, in __init__
2023-11-14 09:12:51 | ERROR | stderr |     self.processed_examples = [
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/site-packages/gradio/helpers.py", line 202, in <listcomp>
2023-11-14 09:12:51 | ERROR | stderr |     [
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/site-packages/gradio/helpers.py", line 203, in <listcomp>
2023-11-14 09:12:51 | ERROR | stderr |     component.postprocess(sample)
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/site-packages/gradio/components/image.py", line 284, in postprocess
2023-11-14 09:12:51 | ERROR | stderr |     return client_utils.encode_url_or_file_to_base64(y)
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/site-packages/gradio_client/utils.py", line 373, in encode_url_or_file_to_base64
2023-11-14 09:12:51 | ERROR | stderr |     return encode_file_to_base64(path)
2023-11-14 09:12:51 | ERROR | stderr |   File "/data/miniconda3/envs/llava/lib/python3.10/site-packages/gradio_client/utils.py", line 346, in encode_file_to_base64
2023-11-14 09:12:51 | ERROR | stderr |     with open(f, "rb") as file:
2023-11-14 09:12:51 | ERROR | stderr | FileNotFoundError: [Errno 2] No such file or directory: LLaVA-Plus/llava/serve/examples/tbs.webp'
```

**Comment by SlongLiu** [comment]
Thanks for the question, we will fix it soon!

**Comment by SlongLiu** [comment]
The problem should be solved in the recent commit. Let me know if you have any questions.

**Comment by tranvanhoa533** [comment]
Thank you for your reply. Similar to this issue, i find those files: examples/tower.png, examples/road.png also do not exist. I have to comment code to ignore those file and run UI.
